package Luokat.test;
// Generated by ComTest BEGIN
import java.util.ArrayList;
import java.util.List;
import org.junit.*;
import Luokat.Reissu;
import Luokat.Saalis;
import static org.junit.Assert.*;
import Luokat.*;
import java.time.LocalDate;
import static Luokat.Reissu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.24 17:03:45 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReissuTest {



  // Generated by ComTest BEGIN
  /** testGetTag40 */
  @Test
  public void testGetTag40() {    // Reissu: 40
    LocalDate pvm = LocalDate.of(2024, 4, 21); 
    List<Saalis> saaliit = new ArrayList<>(); 
    Reissu r = new Reissu(pvm, "Helsinki", "aurinkoinen", saaliit, false); 
    assertEquals("From: Reissu line: 55", pvm, r.getPaivamaara()); 
    assertEquals("From: Reissu line: 56", "Helsinki", r.getSijainti()); 
    assertEquals("From: Reissu line: 57", false, r.getpoistetaanko()); 
    assertEquals("From: Reissu line: 58", saaliit, r.getSaaliit()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSToDate104 */
  @Test
  public void testSToDate104() {    // Reissu: 104
    assertEquals("From: Reissu line: 105", null, sToDate("12.43 Å() 2004")); 
    assertEquals("From: Reissu line: 106", LocalDate.of(2004,4,12), sToDate("12.4.2004")); 
    assertEquals("From: Reissu line: 107", null, sToDate(" 12    3,2004")); 
    assertEquals("From: Reissu line: 108", LocalDate.of(2004,4,12), sToDate("12/4 2004")); 
    assertEquals("From: Reissu line: 109", LocalDate.of(2004,4,12), sToDate("12 4,2004")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testReissu161 */
  @Test
  public void testReissu161() {    // Reissu: 161
    Reissu r = new Reissu("5|02.03.2024|Rovaniemi|kylmä"); 
    assertEquals("From: Reissu line: 163", 5, r.getTag()); 
    assertEquals("From: Reissu line: 164", LocalDate.of(2024, 3, 2), r.getPaivamaara()); 
    assertEquals("From: Reissu line: 165", "Rovaniemi", r.getSijainti()); 
    assertEquals("From: Reissu line: 166", "kylmä", r.getKeli()); 
    assertEquals("From: Reissu line: 167", false, r.getpoistetaanko()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString197 */
  @Test
  public void testToString197() {    // Reissu: 197
    LocalDate pvm = LocalDate.of(2023, 5, 10); 
    Reissu r = new Reissu(pvm, "Oulu", "selkeä", new ArrayList<>(), false); 
    String tallennus = r.toString(); 
    assertEquals("From: Reissu line: 201", true, tallennus.matches("\\d+\\|10\\.05\\.2023\\|Oulu\\|selkeä")); 
  } // Generated by ComTest END
}