package Luokat.test;
// Generated by ComTest BEGIN
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.Before;
import org.junit.Test;
import Luokat.Reissu;
import Luokat.Reissut;
import Luokat.Tulkki;
import Luokat.Saaliit;
import static org.junit.Assert.*;
import org.junit.*;
import Luokat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.28 08:58:48 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReissutTest {



  // Generated by ComTest BEGIN
  /** testPaivamaaraToInt108 */
  @Test
  public void testPaivamaaraToInt108() {    // Reissut: 108
    Saaliit saaliita = new Saaliit(8); 
    Reissut test = new Reissut(saaliita); 
    test.getReissut().clear(); 
    Reissu t0 = new Reissu(Reissu.sToDate("1.12.2323"), "ka", "pilvi", new ArrayList<>(), false); 
    Reissu t1 = new Reissu(Reissu.sToDate("12.12.2023"), "jk", "sade", new ArrayList<>(), false); 
    Reissu t2 = new Reissu(Reissu.sToDate("12.12.1223"), "sk", "aurinko", new ArrayList<>(), false); 
    Reissu t3 = new Reissu(Reissu.sToDate("15.11.2024"), "ka", "pilvi", new ArrayList<>(), false); 
    test.lisaaListaan(t1); 
    test.lisaaListaan(t2); 
    test.lisaaListaan(t3); 
    test.lisaaListaan(t0); 
    assertEquals("From: Reissut line: 134", 4, test.getReissut().size()); 
    t1.poistetaan(); 
    test.removeReissu(); 
    assertEquals("From: Reissut line: 138", 3, test.getReissut().size()); 
  } // Generated by ComTest END
}