package Luokat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Luokat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.27 13:23:25 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class SaaliitTest {



  // Generated by ComTest BEGIN
  /** testLisaa29 */
  @Test
  public void testLisaa29() {    // Saaliit: 29
    Saaliit saaliit = new Saaliit(1); 
    Saalis s = new Saalis("iso", "ahven", "lippa", "sininen"); 
    saaliit.lisaa(s); 
    Saalis s2 = new Saalis("iso", "ahven", "lippa", "sininen"); 
    saaliit.lisaa(s2); 
    assertEquals("From: Saaliit line: 35", 2, saaliit.getKoko()); 
  } // Generated by ComTest END
}