package Luokat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Luokat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.18 12:48:46 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class SaalisTest {



  // Generated by ComTest BEGIN
  /** testSetReissunTagi48 */
  @Test
  public void testSetReissunTagi48() {    // Saalis: 48
    String rivi = "1|1|3|1|2|sininen"; 
    Tulkki lajit = new Tulkki(System.getProperty("user.dir") + "/../lajit.dat"); 
    Tulkki vieheTulkki = new Tulkki(System.getProperty("user.dir") + "/../vieheTyypit.dat"); 
    Tulkki kokoTulkki = new Tulkki(System.getProperty("user.dir") + "/../koot.dat"); 
    Saalis s = new Saalis(rivi, lajit, vieheTulkki, kokoTulkki); 
    s.setReissunTagi(2); 
    assertEquals("From: Saalis line: 55", 2, s.getReissunTagi()); 
  } // Generated by ComTest END
}