package fxKaljoja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxKaljoja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.27 13:23:03 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class KalojaGUIControllerTest {
}